index:
    path: /reset-password
    methods:
        - POST
    controller: App\Framework\Controller\RequestResetPasswordController

login:
    path: /login
    methods:
        - POST
    controller: App\Framework\Controller\LoginController
